# Nơi khai báo thông tin cấu hình và giá trị cấu hình cho các thư viện được sử dụng trong dự án

server:
  port: 8091


mailServer:
  host: smtp.gmail.com
  port: 587
  email: cp.nguyentienthanh@gmail.com
  password: uqlg wnbz spro zmpy
  protocol: smtp
  isSSL: false

secretKey:
  key: y1Dtj5V0BHHGdH1lsu967g5u+iFLiJyhlpmMd4woJpE=
